import{a as p,i,S as b}from"./assets/vendor-B6jJ9_I0.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const h of s.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&a(h)}).observe(document,{childList:!0,subtree:!0});function o(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(r){if(r.ep)return;r.ep=!0;const s=o(r);fetch(r.href,s)}})();const L="47642330-01773e177615e156ed5ec02c5";p.defaults.baseURL="https://pixabay.com/api/";const f=async(t,e=1,o=20)=>{try{return(await p.get("/",{params:{key:L,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:e,per_page:o}})).data}catch(a){console.error(a)}},y=t=>`
        <li class="image-card">
            <a href="${t.largeImageURL}" target="_blank">
                <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
                <div class="image-info">
                    <p><b>Likes</b> ${t.likes}</p>
                    <p><b>Views</b> ${t.views}</p>
                    <p><b>Comments</b> ${t.comments}</p>
                    <p><b>Downloads</b> ${t.downloads}</p>
                </div>
            </a>
        </li>
    `,v=t=>{const e=document.querySelector(".gallery");e.innerHTML="";const o=t.map(y).join("");e.insertAdjacentHTML("beforeend",o)},w=t=>{const e=document.querySelector(".gallery"),o=t.map(y).join("");e.insertAdjacentHTML("beforeend",o)},S=document.querySelector("#search-bar-form"),d=document.querySelector("body > .loader"),l=document.querySelector("#btn-load-more"),g=document.querySelector(".load-more-block .loader");let c=1,m=15,u,n;const q=async t=>{t.preventDefault();try{if(n=t.target.elements.search.value,n.trim().length===0)return;l.classList.remove("show"),d.classList.add("is-active"),c=1;const o=await f(n,c,m);(!o.hits||!o.hits.length)&&i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),v(o.hits),c*m<o.totalHits?l.classList.add("show"):i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),u=new b(".gallery a",{captionsData:"alt",captionDelay:250}),u.refresh(),d.classList.remove("is-active")}catch(e){console.error(e),i.error({message:e.message,position:"topRight"}),d.classList.remove("is-active")}},R=async t=>{try{if(!n||n.trim().length===0)return;c+=1,l.classList.remove("show"),g.classList.add("is-active");const e=await f(n,c,m);(!e.hits||!e.hits.length)&&i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),w(e.hits);const o=document.querySelector(".image-card"),{height:a}=o.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"}),g.classList.remove("is-active"),c*m<e.totalHits?l.classList.add("show"):i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),u.refresh()}catch(e){console.error(e),i.error({message:e.message,position:"topRight"}),d.classList.remove("is-active")}};S.addEventListener("submit",q);l.addEventListener("click",R);
//# sourceMappingURL=index.js.map
